export const generateMetadata = ({ params: { id, name } }) => {
  return {
    title: name.replace(/-/g, " "),
    description: "Generated by create next app",
    keywords: "nextjs, clerk, next-auth, tailwindcss",
  };
};

const layout = ({children}) => {
  return <>{children}</>;
};
export default layout;
