import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";

const openSans = Open_Sans({
	displayName: "Open Sans",
	subsets: ["latin"],
});

export const metadata = {
	title: "Movie Mania",
	description: "Generated by create next app",
	keywords: "nextjs, clerk, next-auth, tailwindcss",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<head>
					<link rel="icon" href="/favicon.ico" />
				</head>
				<body className={openSans.className}>
					<Header />
					<main>{children}</main>
				</body>
			</html>
		</ClerkProvider>
	);
}
